### PR TITLE
Add pcc as a system compiler.

### PR DESCRIPTION
**Pull request by ibara**
Fix the tendrils necessary for this.
Remove a now redundant typedef in usr.bin/diff

I'm only hooking up pcc right now, not libpcc.a (don't worry, you can still use pcc just fine).
The original usr.bin/cpp gets unhooked from the build but leaving the source in if people want.

Oh, and the man pages for pcc aren't hooked up yet.

### CODE REVIEW

**Comment by sergev** [comment]
Good!
As I can see, the compiler is installed to the /usr/lib/pcc/mipsel-unknown-litebsd0.1 directory. Wouldn't it make sense to reconfigure it a bit to use /usr/lib/pcc/mipsel-elf-litebsd path?

**Comment by ibara** [comment]
Actually that's where the include headers and libraries will live. The actual compiler is in /usr/libexec with the frontends in /usr/bin
My thought process is the traditional *BSD triplet is arch-unknown-nameofbsd${OS_REV} and we should stick to that to make bringing up LiteBSD as a supported platform as painless for us and as least surprising to others as possible.

**Comment by sergev** [comment]
I just don't like the 'unknown' part. Can we omit it? 
I'm also not sure the ${OS_REV} suffix makes sense. 
LiteBSD is a tiny embedded platform. 
It's highly unlikely somebody will try to install pcc toolchains of different versions on it.

**Comment by ibara** [comment]
We could omit it, but then the unknown part is still there (it's just implicit).
I guess with me having 10 years in *BSD land the unknown part doesn't bother me anymore :-)

The ${OS_REV} suffix is already optional. You can omit it now if you want. Again, it's more traditional that this is what the BSDs do. While you're totally right that it's highly unlikely a user hurts themselves by installing an outdated version of the compiler, I would only add that keeping ${OS_REV} might be useful for us to track history and development.

**Pull request merged**
